### ISSUE TITLE
Can't use on aws with php-python combination

### ISSUE THREAD

**Issue by almakorte61** [DeepLcom/deepl-python#10]
I want to use this  API for my university project, but can't do it with php:

This is my php code:

```PHP
              <?php
                echo "alma: ";
                $original = 'rák';
                $output = passthru("python3 search.py $original");
              ?>
```
and in `search.py`
```python
#!/usr/bin/env python
import sys
import requests
import deepl
import logging

logging.basicConfig()
logging.getLogger('deepl').setLevel(logging.DEBUG)

print "translated: \t"
translator = deepl.Translator("mykey")
result = translator.translate_text("Hello, world!", target_lang="FR")
print(result)
print '<br>'
```

And I got only `alma:` text back. 

Also tried like: `system("python3 -m deepl --auth-key=MYKEY text --to=DE 'Text to be translated.'");` but nothing. I didn't find anything in PHP error log. 

BUT if I want to use in aws command line as [was mentioned](https://github.com/DeepLcom/deepl-python#command-line-interface) than I got the correct answers. 

I also opened a stackoverflow error about this: https://stackoverflow.com/questions/69861167/how-to-parse-answers-with-deepl-api

**Comment by daniel-jones-deepl** [comment]
I'm going to close this issue. @almakorte61 please comment again if you have further problems.
