### ISSUE TITLE
translate_document_from_filepath fails to recognise XML files

### ISSUE THREAD

**Issue by MasonLyons** [DeepLcom/deepl-python#102]
When trying to translate an xml document using the translate_document_from_filepath method an error is returned.
```python
import deepl

input_filename = "test.xml"
source_language = "en"
output_filename = "test_out.xml"
output_language = "es"

translator = deepl.Translator(auth_key)
translator.translate_document_from_filepath(
    input_path=input_filename,
    output_path=output_filename,
    source_lang=source_language,
    target_lang=output_language,
)
```
`Bad request, message: Failed to get the document_type from the file extension (test.xml).`

**Comment by JanEbbing** [comment]
Document translation does not support `xml` files, you would need to send it as a text translation request by using XML tag handling. See [docs](https://developers.deepl.com/docs/api-reference/document) for document translation and [XML tag handling](https://developers.deepl.com/docs/xml-and-html-handling/xml).
