### ISSUE TITLE
[Feature Request] Make auto-retry toggleable

### ISSUE THREAD

**Issue by Bikatr7** [DeepLcom/deepl-python#105]
Hello!

I was wondering if you guys could add a way to toggle the auto-retry when translating

I know of course that this is best practice, but I have a use case for when I'd like to add my own decorator, instead of the one already provided (custom retrying, logging, different timing etc.). And currently doing that seems to cause conflicts.

I don't really have the time right now to look into how to properly implement this myself, so I wish to request this feature.

Thanks.

**Comment by JanEbbing** [comment]
Hi, you should be able to do this by setting `deepl.http_client.max_network_retries = 0` after importing `deepl` and before using the `Translator`.  Please see the section "Configure automatic retries" in the `README.md`

**Comment by Bikatr7** [comment]
Oops. I had incorrectly assumed it wasn't possible. My apologies.

**Comment by JanEbbing** [comment]
No worries, please let me know if you encounter any issues :)
