### ISSUE TITLE
can't use my auth key, and can't sign up to the API plan for free trial

### ISSUE THREAD

**Issue by Yann-C-INN** [DeepLcom/deepl-python#106]
Hello. I'll start by mentioning that I have read [Issue 62](https://github.com/DeepLcom/deepl-python/issues/62) and the documentation in the website, with no help.

I signed up for the Pro-advanced plan and I have the API key:
![image](https://github.com/DeepLcom/deepl-python/assets/130037694/23f79bed-293c-446c-a800-23b4c7898158)
I realized that it might not be the proper plan, so I tried to sign up for the free [API plan](https://www.deepl.com/pro-api?cta=header-pro-api) but when I try to sign up (as i understand, these are two different usecases) it says that my Email address is already at use.

I tried accessing the API using python but I get this error: 
```
raise AuthorizationException(
deepl.exceptions.AuthorizationException: Authorization failure, check auth_key, message: This account is not allowed to access the API.
```

Not sure what I am doing wrong. On one hand, my current auth key is not valid, and on the other it doesnt let me signing up for a new plan (the API plan) so I can test a valid auth key.

I hope I made my problem clear for you to be able to assist.
Yann

**Comment by JanEbbing** [comment]
Hi Yann, sorry for the frustrations. Unfortunately the Web Translator and API accounts are separate. The API Key for CAT tools you shared in your screenshot is only for CAT tools, and not for the public API, hence the error.

So the way for you to get an API key would be to create a free API account. Do you have a second email you could use to sign up? If you already have an account for that e-mail address for the Web translator, it won't let you create a second account with the same email address.

**Comment by Yann-C-INN** [comment]
> Hi Yann, sorry for the frustrations. Unfortunately the Web Translator and API accounts are separate. The API Key for CAT tools you shared in your screenshot is only for CAT tools, and not for the public API, hence the error.
> 
> So the way for you to get an API key would be to create a free API account. Do you have a second email you could use to sign up? If you already have an account for that e-mail address for the Web translator, it won't let you create a second account with the same email address.

Thanks for the response.
I would really like to avoid using a different (personal) email account. I contacted support too. Is it possible to delete my current account so I can sign up again to the proper plan?

It is a bit odd that they are linked in the sense it's the same Email address but unlinked in the sense those are two different API keys and once you have one account you cant sign up for the other :/

**Comment by JanEbbing** [comment]
You can try using an email alias as described [here](https://gmail.googleblog.com/2008/03/2-hidden-ways-to-get-more-from-your.html) (the first part, with the plus sign) to sign up with a different email that is still yours, many mail providers support this. I am not sure about the credit card part, sorry.

**Comment by Yann-C-INN** [comment]
Thank you very much for your assistance. I'm on it as we speak (well, write..).

Have a nice rest of the day.
Yann
