### ISSUE TITLE
Proxy usage?

### ISSUE THREAD

**Issue by LeMoussel** [DeepLcom/deepl-python#11]
Does deepl-python provide out of the box usage of proxies?

For example, I define my proxies config as a dictionary and pass it to `deepl.Translator`.

**Comment by daniel-jones-deepl** [comment]
Hi @LeMoussel, thank you for raising this issue. Unfortunately proxy support is missing, we'll add it soon.

**Comment by LeMoussel** [comment]
OK. As soon as this is added I will test it.

**Comment by daniel-jones-deepl** [comment]
Hi @LeMoussel, proxy support has now been added in v1.3.1, to use it pass a `proxy` parameter to `Translator()`. Here is the new entry in the readme: https://github.com/DeepLcom/deepl-python/tree/v1.3.1#proxy-configuration
