### ISSUE TITLE
Document_key and document_id for checking translation status is missing

### ISSUE THREAD

**Issue by shopkueche** [DeepLcom/deepl-python#12]
We´d like to translate a large amount of files. Mostly these files are "TXT" and have up to 1 Mio. signs. (We know about the API-Limitations)

If we use this code we will get back an fully translated file:
```
translator.translate_document_from_filepath(
    "Instruction Manual.docx",
    "Bedienungsanleitung.docx",
    target_lang="DE",
    formality="more"
)
```
### Problem:
In some cases, when the file is very large or the script goes into the timeout cause the API of DeepL is slow, we lose the translation and have to start our script over again.

### Solution:
We would like to see the **document_ID and document_id** as output in the console when starting the script.
If the the script fails, we can grab and download the translation manually from the server. (See "Downloading translated documents" in DeepL-API-Docs)

**Comment by daniel-jones-deepl** [comment]
Hi @shopkueche, thanks for raising this issue. To solve your problem, it might be sufficient to extend your code to catch `deepl.DocumentTranslationException`; this exception is thrown if an error occurs after the document has been uploaded and it includes the document ID and key.

```
try:
    translator.translate_document_from_filepath(...)
except deepl.DocumentTranslationException as err:
    print(f"Error occurred while translating document")
    print(f"Document ID: {err.document_request.document_id}")
    print(f"Document key: {err.document_request.document_key}")
```

This depends on how your script handles a timeout and whether exceptions are handled gracefully in that case.

If exceptions are not handled, you could instead use the lower-level document translation functions: `translate_document_upload`, `translate_document_get_status` and `translate_document_download`; the other document translation functions wrap these functions. You can see how the lower-level functions are used here: https://github.com/DeepLcom/deepl-python/blob/v1.3.1/deepl/translator.py#L812. `translate_document_upload` returns a handle containing the document ID and key.

**Comment by daniel-jones-deepl** [comment]
I will close this issue now, if there are further issues please reopen it.
