### ISSUE TITLE
AttributeError: module 'deepl' has no attribute 'Translator'

### ISSUE THREAD

**Issue by YanYeek** [DeepLcom/deepl-python#14]
![image](https://user-images.githubusercontent.com/48875922/142732037-31805e2a-4dfc-4887-87e8-a21d57db25a7.png)

**Comment by benjamin-eikel-deepl** [comment]
This looks like the same problems as in #3 and #13: You have a file called `deepl.py` which conflicts with the import of `deepl`. Please rename that file.

**Comment by YanYeek** [comment]
Tanks,That's a low-level mistake for me!

**Comment by YanYeek** [comment]
> This looks like the same problems as in #3 and #13: You have a file called `deepl.py` which conflicts with the import of `deepl`. Please rename that file.

Tanks,That's a low-level mistake for me!

**Comment by YanYeek** [comment]
> This looks like the same problems as in #3 and #13: You have a file called `deepl.py` which conflicts with the import of `deepl`. Please rename that file.
Thank you, that's a low-level mistake for me!
