### ISSUE TITLE
Authorization failure, check auth_key, message: Wrong endpoint

### ISSUE THREAD

**Issue by NicolasMsk** [DeepLcom/deepl-python#16]
Hello,
When i'm using a free DeepL account, the auth_key works but when i'm using a pro account, the aut_key is wrong with the folloing error : Authorization failure, check auth_key, message: Wrong endpoint

here is my code : 

!pip install --upgrade deepl
import deepl
import os

os.environ['API_KEY'] = 'xxxxxxxxxxxxxxxxxxxxxxxx'
translator = deepl.Translator(os.getenv('API_KEY'))

result = translator.translate_text("Hello, world!", target_lang="FR")
print(result)  

I don't understand what i have to do to use my Pro account. 

Thanks

**Comment by daniel-jones-deepl** [comment]
Hi @NicolasMsk, thanks for opening this issue. Your usage seems correct. The problem might be that your Pro account is not a DeepL API Pro account; the DeepL API is only available to DeepL API Free and DeepL API Pro accounts.

**Comment by NicolasMsk** [comment]
Oh yes sorry i was wrong i have a DeepL Pro Advanced account. But how can i use the API in Python with that type of account? Thx for your reactivity.

**Comment by daniel-jones-deepl** [comment]
Unfortunately that is not possible. So you can continue using your DeepL API Free account, or upgrade to an DeepL API Pro account.

**Comment by NicolasMsk** [comment]
Thank you for the answers!

Have a nice day
