### ISSUE TITLE
Problems when NOT using Deepl_API-Key from environment

### ISSUE THREAD

**Issue by JoergZ2** [DeepLcom/deepl-python#17]
I am currently practicing with the Python library, initially only with the translation of simple text sections. For this I have disabled the following line:
`#translator = deepl.Translator(os.getenv("DEEPL_AUTH_KEY"))`
and instead
`translator = MyAPIKey`
(with the real key). This resulted in an error message:
```
  File "./deepl_trans.py", line 9
    translator=XXXXXXXe-XXXX-XXXX-XXXXXXXXXXXX:fx
                      ^
SyntaxError: invalid syntax
```
The ^character is just one position before  "e". So I put the key in quotes. Then it throws this error message:
```
Traceback (most recent call last):
  File "./deepl_trans.py", line 11, in <module>
    result = translator.translate_text("Hello, world!", target_lang="FR")
AttributeError: 'str' object has no attribute 'translate_text'.

```
What do I have to do if I DON'T want to set the deepl API key as an environment variable but hard coded or as input? (As soon as I set the Api key as an environment variable the script works fine.)

Translated with www.DeepL.com/Translator (free version) ;-)

**Comment by daniel-jones-deepl** [comment]
Hi @JoergZ2,
Try replacing the line
```#translator = deepl.Translator(os.getenv("DEEPL_AUTH_KEY"))```
with:
```translator = deepl.Translator("XXXXXXXe-XXXX-XXXX-XXXXXXXXXXXX:fx")```
(But with the Xs replaced with your key)

**Comment by daniel-jones-deepl** [comment]
Or alternatively:
```
deepl_auth_key = "XXXXXXXe-XXXX-XXXX-XXXXXXXXXXXX:fx"
translator = deepl.Translator(deepl_auth_key)
```

**Comment by JoergZ2** [comment]
OMG! Where is the stone I can hide under! Thanks!
