### ISSUE TITLE
Rate throttling when approaching account limits 

### ISSUE THREAD

**Issue by leekimber** [DeepLcom/deepl-python#18]

**Comment by leekimber** [comment]
Redundant suggestion now that I've looked at the code properly!

**Comment by daniel-jones-deepl** [comment]
Hi @leekimber, sorry that I did not respond earlier.

Yes, we have built a failure-retry strategy with exponential-backoff into this client, so it will respond dynamically to rate-throttling. If you have feedback on that I'd be interested to hear it.

However your idea about stopping requests when getting *near* the character usage limit is interesting, and could be useful in some use-cases. That is not implemented by this library, but would be possible to implement in wrapper code.

**Comment by leekimber** [comment]
Hi @daniel-jones-deepl.

No problem. I'm just starting to rewrite my wrappers and will let you know if anything unexpected crops up.

The issue I originally coded around was more of a product management issue than a coding issue. That is, it was about enabling me - and any deepl API customer - to monitor and manage their own translation delivery capacity (and therefore their delivery liabilities and payment/cost streams). This to ensure there is no abrupt halt or unexpected bottleneck in translation capacity.

Although I'd specified code as a workaround in my deepl_api class, there are more graceful ways for me to implement it, which I'll try in a new wrapper.
