### ISSUE TITLE
Can't create an account for free-api

### ISSUE THREAD

**Issue by AntonUspehov** [DeepLcom/deepl-python#2]
Hello DeepL team, thanks for a great product!

I want to use your API to create an iOS shortcut, but I can't find how to create an account to use **free** API on the page from your documentation - https://www.deepl.com/pro/select-country?cta=menu-login-signup/#developer

I don't see my country in the list, so I can't create an account. Can you help me with that?

**Comment by AntonUspehov** [comment]
I receive an error like - `We can only accept credit cards registered in countries where DeepL Pro is available`, but I only want to use your free-api for the community's sake.

**Comment by daniel-jones-deepl** [comment]
Hi Anton, thanks!

Unfortunately it is not possible to create a DeepL API Free account in [countries where DeepL Pro is not available](https://support.deepl.com/hc/en-us/articles/360020016339-DeepL-Pro-is-not-available-in-my-country). We’re working on extending availability to more countries though.

**Comment by AntonUspehov** [comment]
Hi @daniel-jones-deepl, I totally understand you.
But how does the API key for free-api relate to the DeepL Pro plan?

Maybe it's possible to make an exception and somehow generate the key? It's for personal use only. What do you think about it?

**Comment by daniel-jones-deepl** [comment]
Hi @AntonUspehov, I’d like to be able to help you with your project, but the current limitation is due to both technical and business reasons. I’ve raised the issue internally, and I’ll let you know if the situation changes; I assume you are based in Ukraine.

**Comment by AntonUspehov** [comment]
Thanks, @daniel-jones-deepl for your try.
Yes, I am from Ukraine.
