### ISSUE TITLE
Translation EN-US EN-GB don't work

### ISSUE THREAD

**Issue by Azru44** [DeepLcom/deepl-python#20]
It seems that these 2 languages are not translated correctly, when you type french text and use EN-US or EN-GB as target language it doesn't translate anything, the text is the same

for exemple translator.translate_text("Bonjour", target_lang='EN-GB') return "Bonjour" and it should return "Hello"

**Comment by daniel-jones-deepl** [comment]
I will close this issue now. If you continue to see this issue, please reply.
