### ISSUE TITLE
deepl.exceptions.AuthorizationException: Authorization failure, check auth_key

### ISSUE THREAD

**Issue by bengadi** [DeepLcom/deepl-python#23]
I have a valide auth_key but i still get this error

**Comment by daniel-jones-deepl** [comment]
Hi @bengadi, this issue could be because your account is not a DeepL API Free or DeepL API Pro account, but some other type of DeepL account. Is this the case?

**Comment by daniel-jones-deepl** [comment]
That is an unusual error. The problem seems to be related to your account. Can you please [create a support request](https://support.deepl.com/hc/en-us/requests/new)? Then we'll be able to look into your account.

**Comment by daniel-jones-deepl** [comment]
I'm closing this issue now, please reopen it if you continue to have errors.
