### ISSUE TITLE
Update the "Chinese" lang to "Chinese simplified" (or appropriate)

### ISSUE THREAD

**Issue by mkinney** [DeepLcom/deepl-python#24]
I used deepl api to update some values in a file and had a native speaker review the changes.

They replied with:
..."it would be better to make this version of Chinese zh-cn since it's done according to Simplified Chinese in Mainland China. That will make space for other variants, like zh-tw which is a different dialect of Chinese used in Taiwan."

**Comment by daniel-jones-deepl** [comment]
Hi @mkinney, thank you for the comment, this is a good question. I've forwarded the question to our language experts, and I'll get back to you when I have a response.

**Comment by daniel-jones-deepl** [comment]
Hi again, you are right. We've prepared the change for the target language `zh` from "Chinese" to "Chinese (simplified)"; it will take some time before the changes are published.
