### ISSUE TITLE
Issue with ignore_tags parameter

### ISSUE THREAD

**Issue by roland71** [DeepLcom/deepl-python#29]
Hello! Running the deepl package with anvil.works (https://pypi.org/project/deepl/1.5.0/) 
Example code: translation_output = translator.translate_text(translation_input target_lang="EN-US", ignore_tags=x)
Getting: NameError: name 'x' is not defined

**Comment by SamueLacombe** [comment]
Hello,

I believe your issue is that are providing an Int instead of a string:

Here is my request and it's working. I believe you just have to replace 'ignore' by 'x'
`translation = client.translate_text(df['SourceTokenized'].tolist(), target_lang=targetLangDeeplCode, tag_handling='html', ignore_tags='ignore', split_sentences="0", preserve_formatting="1", formality=formality)`

**Comment by daniel-jones-deepl** [comment]
Hi @roland71, yes @SamueLacombe is right (thank you Samuel!)

The `ignore_tags` argument expects either a string (`..., ignore_tags='x', ...`) or list of strings (`..., ignore_tags=['x', 'another_tag_to_ignore'], ...`).

**Comment by roland71** [comment]
@daniel-jones-deepl 
but this only works if an opening tag is followed by a closing tag - right? if, for example, the string that is not to be translated is marked with an opening tag at the beginning and at the end, then this string will still be translated.

**Comment by SamueLacombe** [comment]
I believe it depend on your argument: tag_handling

if tag_handling='html' then you need opening and closing.
if tag_handling='xml' then it's just a tag.

**Comment by daniel-jones-deepl** [comment]
Hi @roland71, apologies that this reply was delayed.

The `ignore_tags` parameter is only used if the `tag_handling` parameter is set to `'xml'`. If instead `tag_handling` is set to `'html'`, then the `ignore_tags` parameter is not used and instead DeepL uses predefined tags that suit HTML. However, we do provide a method to ignore HTML tags if necessary, [explained here in our documentation)[https://www.deepl.com/docs-api/handling-html-(beta)/disabling-translation-of-elements/).

In @SamueLacombe's example code above, as `tag_handling` is set to `'html'`, the `ignore_tags` parameter will be ignored. Sorry for the confusion.

Here is a corrected example using XML:
```
text = "This will be translated.<x>This will not be translated.</x>"
result = translator.translate_text(text, target_lang="de", tag_handling="xml", ignore_tags="x")
print(result.text)  # Dies wird übersetzt werden.<x>This will not be translated.</x>
```

Regarding opening & closing tags, for best results you should ensure you match opening tags with closing tags. We do use some heuristics to try to fix invalid XML/HTML, but the results may be unpredictable.
