### ISSUE TITLE
Unable to import and make authorization

### ISSUE THREAD

**Issue by unnidiametos** [DeepLcom/deepl-python#3]
AttributeError: partially initialized module 'deepl' has no attribute 'Translator' (most likely due to a circular import)

AuthorizationError:

**Comment by daniel-jones-deepl** [comment]
Hi @unnidiametos, there might be a simple fix: in case your file is named "deepl.py", try renaming it, for example: "my_deepl_script.py".

If that doesn't fix it, can you please provide an example that reproduces the error, and say which Python version you are using?

**Comment by unnidiametos** [comment]
It is still producing the same error after renaming. I am using python 3.9.0

**Comment by daniel-jones-deepl** [comment]
Okay, then can you please share a minimal example file that produces your problem? Please make sure that your auth-key is not included.

**Comment by unnidiametos** [comment]
import deepl
auth_key = {
    'host' : "https://api.deepl.com/v2/translate?",
    'auth_key': "xxxxxxxxxxxxxxxxxxxxxxxxxxx"}

text = "Wie geht es dir?"
target_language = "EN-US"

translator = deepl.Translator(auth_key['auth_key'])
result = translator.translate_text(text, target_lang=target_language)
translated_text = result.text

print(translated_text)

**Comment by daniel-jones-deepl** [comment]
Thank you for sharing the example. I don't see anything wrong with your example, and it works fine for me.

Maybe you have another file in the same directory named "deepl.py", or a directory named "deepl"? This would cause the import error you are seeing.

**Comment by unnidiametos** [comment]
Thanks for the comment. I recognized that the folder name was 'deepl'. When I changed it the import is working.

But when I got to 
result = translator.translate_text(text, target_lang=target_language)
I am getting error as:
Traceback (most recent call last):
  File "C:\Users\unnik\OneDrive\Desktop\my_deepl\my_deepl_script.py", line 10, in <module>
    result = translator.translate_text(text, target_lang=target_language)
  File "C:\Users\unnik\AppData\Local\Programs\Python\Python39\lib\site-packages\deepl\translator.py", line 504, in translate_text
    request_data = self._check_language_and_formality(
  File "C:\Users\unnik\AppData\Local\Programs\Python\Python39\lib\site-packages\deepl\translator.py", line 428, in _check_language_and_formality
    self._check_valid_languages(source_lang, target_lang)
  File "C:\Users\unnik\AppData\Local\Programs\Python\Python39\lib\site-packages\deepl\translator.py", line 411, in _check_valid_languages
    target_lang == lang.code for lang in self.get_target_languages()
  File "C:\Users\unnik\AppData\Local\Programs\Python\Python39\lib\site-packages\deepl\translator.py", line 745, in get_target_languages
    self._target_languages_cached = self._request_languages(
  File "C:\Users\unnik\AppData\Local\Programs\Python\Python39\lib\site-packages\deepl\translator.py", line 375, in _request_languages
    self._raise_for_status(status, content, json)
  File "C:\Users\unnik\AppData\Local\Programs\Python\Python39\lib\site-packages\deepl\translator.py", line 345, in _raise_for_status
    raise AuthorizationException(
deepl.exceptions.AuthorizationException: Authorization failure, check auth_key

Could you please help me with this also

**Comment by daniel-jones-deepl** [comment]
Great.

To solve this new problem, you could check that your authentication key is exactly as it appears on [your DeepL Pro Account page](https://www.deepl.com/pro-account/) - check you don't have leading or trailing spaces, for example.

If you still have problems with the authorization, you could [submit a support request](https://support.deepl.com/hc/requests/new), so that we can check your authentication key.

**Comment by LivingDeadCloud** [comment]
Sorry to bump into the conversation, but I got the same error (I'm sure the key was copied correctly).
I opened a ticket as @daniel-jones-deepl suggests, but since I'm having this issue as well, maybe there is an underlying bug here.

Hope this info is useful for you

**Comment by daniel-jones-deepl** [comment]
Hi @LivingDeadCloud, no problem, thank you for commenting about your problem.

**Comment by blacchollywood** [comment]
Is there any reason why this problem might occur?

I am working with DeepL in the Pythonanywhere cloud and have installed the package correctly.

However when I run my script  I only get the error

`"/home/alexjeser/.virtualenvs/gpt3x/gcm_reviews_gpt3y.py", line 23, in <module>
    translator = deepl.Translator(auth_key)
AttributeError: module 'deepl' has no attribute 'Translator'`

Any advice?

**Comment by daniel-jones-deepl** [comment]
Hi @blacchollywood, to eliminate the possibility of importing the wrong module, you could try inspecting `deepl.__file__`; it should be a file `deepl/__init__.py`, beginning with the line `# Copyright 2022 DeepL SE (https://www.deepl.com)`.

If this is all as expected, then there could be an issue with the library in PythonAnywhere.
