### ISSUE TITLE
source_lang problem 

### ISSUE THREAD

**Issue by idrisay** [DeepLcom/deepl-python#34]
Hello, I just want to translate from German to French and I don't want to translate the English part in a sentence. For example, when I try to translate "Das is meine mutter, beautiful woman"  in deepl translate API it returns 'c'est ma mère, belle femme', but I just want to German part of the sentence and return 'c'est ma mère, beautiful woman'.

And in some requests, all my sentences are in English, and I don't want to translate them to French because I assigned source_lang as DE and target_lang FR, but it translates English sentence to French.

**Comment by daniel-jones-deepl** [comment]
Hi Idris,

This is an interesting use case, but unfortunately our API currently does not support it. Our API attempts to translate all the input into the target language, it doesn't select which parts of the input text match the source language. The source language is used to select a model trained for the language pair.

I am not sure in your use case whether you have information about which parts of the input text are in English; I suspect not. If you *do* have this information, you could construct a workaround using XML tag_handling and wrapping the English parts in ignored tags.
