### ISSUE TITLE
Authentication based on enterprise proxy server

### ISSUE THREAD

**Issue by maruedt** [DeepLcom/deepl-python#37]
In browser-based usage, we have a proxy server with which we connect, eg. `deepl.<enterprise domain>.ch`. This grants us access to DeepL Pro without the need for a login. Is it possible to use our enterprise proxy server to access DeepL Pro API without using an authentication key? 

I could not find anything on this topic in the documentation. As far as I saw, `deepl.Translator` always raises an exception, if no authentication key is given.

**Comment by daniel-jones-deepl** [comment]
Hi @maruedt, thanks for the question.

It sounds like you are using IP-based enterprise login. This is not currently available for the API; all API requests require an authentication key.

This could be possible if the proxy server can be configured to add an Authentication header to incoming requests; this is something we could look into if necessary.

**Comment by maruedt** [comment]
Thanks for the reply and the clarification. I was hoping that there might be a quick fix. Since it is a small side project of mine, I don't think it is necessary to look deeper into any solutions.
