### ISSUE TITLE
How to set keywords that are not translated by all languages

### ISSUE THREAD

**Issue by declandragon** [DeepLcom/deepl-python#39]
DeepL Pro API

**Comment by daniel-jones-deepl** [comment]
Hi @declandragon, thanks for creating this issue.

I'm not sure what you mean exactly. Would you like to be able to translate something like:

> Dear {{customer_name}}, thank you for subscribing to emails about {{product_name}}.

to get an output like the following?

> 亲爱的{{customer_name}}，感谢您订阅关于{{product_name}}的电子邮件。

You could try using XML tag-handling to achieve this, by wrapping your keywords with XML tags; the XML tags will be reproduced in the output in the correct locations.

**Comment by declandragon** [comment]
thank you
