### ISSUE TITLE
A issue about deepL browser extension

### ISSUE THREAD

**Issue by httpsColon** [DeepLcom/deepl-python#53]
that is the browser extension pronunciation function, which actually pronounces the translated text instead of the original, it is ridiculous.

**Comment by daniel-jones-deepl** [comment]
Hi @httpsColon, I've asked the team responsible for the DeepL Chrome extension about this issue -- they are aware of this issue and it is on their to-do list.

**Comment by daniel-jones-deepl** [comment]
This should now be addressed in the DeepL Chrome extension.
