### ISSUE TITLE
[Feature Request?] Ability to set a preferred gender for outputs with gendered languages

### ISSUE THREAD

**Issue by qexat** [DeepLcom/deepl-python#54]
Apologies if this issue is irrelevant.

Is there a way to specify a preferred gender for gendered languages such as French or Spanish in a way that the translation that comes up matches it?

For instance, with preferred gender set to feminine, from english to french:
Input: "I've come to this city"
Output: "Je suis venue dans cette ville" (instead of "Je suis venu dans cette ville")

Otherwise it would be very nice if this was added. In fact, this is kind of a feature request for DeepL as a whole, not just the API, but I didn't know where else to ask.
I guess this would take a certain time to implement, too.

**Comment by daniel-jones-deepl** [comment]
Hi @qexat, thanks for creating this issue. It is okay to raise issues here on wider DeepL topics; I communicated your issue to the team.

No, unfortunately this is not currently possible. We want to improve our results with regards to gendered language and it is in our plan, but I cannot offer a timeline for when it might be available.

**Comment by qexat** [comment]
Understood, thank you very much for your answer.

**Comment by qexat** [comment]
@seekuehe Hi, I just saw that you marked this issue as not planned -- is it possible to know the reason for it? Thank you in advance.

**Comment by seekuehe** [comment]
Hi @qexat, this ticket is closed _not_ because there are no efforts towards this particular topic but more for issues tracking hygiene. Within our own team which takes care of the client libraries, we have no immediate tasks regarding this. 

When this feature is ready, it will be announced and the relevant updates will appear in the libraries but as Daniel mentioned earlier, we do not have a concrete timeline we can give users.

**Comment by qexat** [comment]
> Hi @qexat, this ticket is closed _not_ because there are no efforts towards this particular topic but more for issues tracking hygiene. Within our own team which takes care of the client libraries, we have no immediate tasks regarding this. 
> 
> 
> 
> When this feature is ready, it will be announced and the relevant updates will appear in the libraries but as Daniel mentioned earlier, we do not have a concrete timeline we can give users.

Got it, thank you for taking your time to reply.
