### ISSUE TITLE
Use python-keyring to get DEEPL_AUTH_KEY

### ISSUE THREAD

**Issue by Freed-Wu** [DeepLcom/deepl-python#56]
use auth key in command line or environment variables is unsafe. Why not use python-keyring?

**Comment by daniel-jones-deepl** [comment]
Hi @Freed-Wu wzy, thanks for the suggestion.

This is a nice suggestion, we could add this in future sometime.

**Comment by JanEbbing** [comment]
This is implemented in commit 51b8b7e502f160f5456415794f2fd0ed4774f9b4
