### ISSUE TITLE
Language availability

### ISSUE THREAD

**Issue by michaelbestokra** [DeepLcom/deepl-python#59]
Hi there.
I'm trying to translate text in korean.

It took me a long time to realise that this is not an available language for your service.
Any request where I send source_lang="ko", I get a 429 error with a {"message":"Too many requests"} response, which is not very indicative of what is going on. 
Is there any way to keep a synced up version of which languages you offer?

Here is the current function that is used to check for valid language.
https://github.com/DeepLcom/deepl-python/blob/4665afe21623d0f8f901af0e9ef53bb7c1ade2a5/deepl/translator.py#L594
Here are a list of languages that you offer:
https://github.com/DeepLcom/deepl-python/blob/4665afe21623d0f8f901af0e9ef53bb7c1ade2a5/deepl/translator.py#L343

**Comment by daniel-jones-deepl** [comment]
Hi @michaelbestokra Michael, thanks for creating this issue. Sorry that this problem costed you a long time, we're looking into it.

You should use the functions `get_source_languages()` or `get_target_languages()` as [explained in the readme](https://github.com/DeepLcom/deepl-python#listing-available-languages) to check the available languages. `_check_valid_languages()` is an internal function that might be changed in future versions.

**Comment by michaelbestokra** [comment]
Hi Daniel, thanks for getting back to me.
Thanks for this, I will use it!
