### ISSUE TITLE
Translation feedback

### ISSUE THREAD

**Issue by RobRomijnders** [DeepLcom/deepl-python#63]
Hey DeepL, thanks for the great translation app!

Where can I submit translation feedback? I cannot find the link on your webpage, so hope you can redirect me from here. 

Translating Spanish to English, 'ola, senorita' is translated as 'hello, senorita'.
The correct version, 'ola, señorita', is translated as 'hello, Miss'.

In other words, the common spanish typo 'ñ'<->'n' is not shown as alternative. You might consider including that typo as an alternative, because it's so common. 

Best regards,
Rob

**Comment by daniel-jones-deepl** [comment]
Hi @RobRomijnders Rob, no we don't have a place to submit translation feedback like this. Thanks for the feedback, I've forwarded it on.
