### ISSUE TITLE
Getting translation alternatives via API

### ISSUE THREAD

**Issue by nielsrolf** [DeepLcom/deepl-python#64]
deepl.com shows me multiple alternatives for a translation:
<img width="406" alt="Screenshot 2023-01-21 at 15 35 28" src="https://user-images.githubusercontent.com/12168515/213871665-5b541cb1-08dc-4592-98c0-625e51b70f77.png">

Is this feature available via the API? I see that deepl.com sends a jsonrpc to retrieve this, but I couldn't find any docs on how to use this endpoint.

**Comment by daniel-jones-deepl** [comment]
Hi @nielsrolf Niels, thanks for creating this issue.

No, for business reasons the DeepL API does not provide the alternative translations.

**Comment by dkrape** [comment]
This is unfortunate. It would be great it this was referenced in the documentation as I spent a bit of time trying to figure out how to return alternate translations.

(For reference: I'm building a flash card app, and wanted to provide suggested translations. Providing a single response is insufficient for words with multiple meanings.)
