### ISSUE TITLE
Add translate nested json

### ISSUE THREAD

**Issue by YuryHrytsuk** [DeepLcom/deepl-python#65]
I want to translate json:

``` python
{'key': {'nested_key': 'value'}}
```
and get  

``` python
{'key': {'nested_key': 'translated_value'}}
```

**Comment by daniel-jones-deepl** [comment]
Hi @YuryHrytsuk, thanks for creating this issue.

We just added [an example for translating JSON](https://github.com/DeepLcom/deepl-python/tree/main/examples/json) in the way you want.
