### ISSUE TITLE
Messy Installation with PIP

### ISSUE THREAD

**Issue by TurtleWilly** [DeepLcom/deepl-python#66]
When installing things with PIP, e.g.

```
pip install deepl --user
```

things get unnecessarily messy in the package target directory afterwards:

```
~/Library/Python/3.7/lib/python/site-packages $ find . -depth 1 -newermt '10 min ago'
…
./CHANGELOG.md
./deepl
./deepl-1.13.0.dist-info
./LICENSE
./SECURITY.md
…
```

The files `CHANGELOG.md`, `LICENSE`, and `SECURITY.md` should be placed inside one of the deepl directories, not into the main package directory. If I was to look for information for deepl, I would check inside the directories, not inside random files where it's not clear instantly where they do belong to. Also if all packages would do it like that only the most recently installed package would have a SECURITY.md, f.ex.

**Comment by JanEbbing** [comment]
Thanks for reporting this! This will be fixed in an upcoming version.

**Comment by JanEbbing** [comment]
This has been fixed, installing the current version via `pip` no longer pollutes the `site-packages` directory
