### ISSUE TITLE
update or add new entries to Glossary 

### ISSUE THREAD

**Issue by vbdata** [DeepLcom/deepl-python#69]
I am not able to find any way to update a current glossary with new entry values. 

entries = translator.get_glossary_entries(glossary_id)
entries["additional"] = "new or updated entry"

I am looking for something similar like this
translator.set_glossary_entries(my_glossary, entries)

or is the only way to update entries in a glossary to fetch the entries, add new values, delete the current glossary and add it again?

I think your library is great! Keep up the good work!

**Comment by seekuehe** [comment]
You listed the correct steps. We do not support updating glossaries, and currently we have no plans to do so.
