### ISSUE TITLE
ConnectionException due to no internet connection is not instantaneous

### ISSUE THREAD

**Issue by YatinChaudhary** [DeepLcom/deepl-python#7]
Hi,

In case of **no internet connection**, when I make a POST/GET request using `requests` library then it instantaneously throw below mentioned connection exception:
> requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api-free.deepl.com', port=443): Max retries exceeded with url: /v2/translate (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001A9772E82B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

However, when I make the same request using `deepl` library under the same circumstances, there is a waiting time of 15 seconds before it throws the below mentioned connection exeption:
> deepl.exceptions.ConnectionException: Connection failed or request timed out.

So, if I am exposing a translation endpoint using `deepl` then there will be a lag in response even though there is no internet connection. This lag is understandable if the endpoint is not reachable or unresponsive, but if internet connection is not available then shouldn't it be instantaneous like `requests` lib?

**Comment by daniel-jones-deepl** [comment]
Hi @YatinChaudhary, thanks for raising this issue.

The `deepl` library retries failed requests following certain errors. I looked into the requests.exception.ConnectionError raised in this case; unfortunately it does not seem there is a reliable way to further differentiate whether this error should be retried.

To get around this issue, you could test the internet connection before making a request using `deepl`.
Alternatively, you could reduce the maximum number of retries: `deepl.http_client.max_network_retries = 1` although doing this will reduce robustness.

**Comment by YatinChaudhary** [comment]
Thanks for your reply.
If it is not possible to identify and decouple different exceptions to decide whether they can be retried or not, then I think I will follow your suggestion for my usecase.
