### ISSUE TITLE
API signup is broken for a week

### ISSUE THREAD

**Issue by anaclumos** [DeepLcom/deepl-python#70]
I know this subject does not fit here, but the API signup portal has been broken for over a week now, and none of the support channels are reachable. When creating a new account and trying to sign up, it gives 

```
Fatal error 00100 occurred during registration. Please try again or contact DeepL Support.
```

and when accessing the next time it gives

```
Something went wrong. Please try again or contact [DeepL Support](https://support.deepl.com/hc/requests/new).
```

clearing the cache or creating a new account does not change anything.

**Comment by JanEbbing** [comment]
Confirmed that API signup works.

**Comment by anaclumos** [comment]
DeepL got it fixed this morning! Huge thanks.

<img width="516" alt="Screenshot 2023-03-30 at 2 45 48 PM" src="https://user-images.githubusercontent.com/31657298/228971664-78ec0c7a-d82b-4ea2-8755-ded2a0c67e8a.png">
