### ISSUE TITLE
add py.typed

### ISSUE THREAD

**Issue by vad** [DeepLcom/deepl-python#71]
Can you please add a `py.typed` empty file inside the library, in order to let mypy know your library is type hinted, and make your users happy?

https://mypy.readthedocs.io/en/stable/installed_packages.html#creating-pep-561-compatible-packages

**Comment by JanEbbing** [comment]
Thanks for this suggestion, we will definitely do this. Right now, this is blocked by our work to get properly typed, but we'll definitely do this.

**Comment by JanEbbing** [comment]
This is in v1.16.0, please let me know if there are any issues with the types.
