### ISSUE TITLE
Convenient request max retries setup

### ISSUE THREAD

**Issue by lukasz-staniszewski** [DeepLcom/deepl-python#87]
Hello, 

are there any plans to allow setting a maximum number of request retries in `deepl.Translator()` args? Or is there any convenient way I can do it by myself without touching the library code?

**Comment by JanEbbing** [comment]
Hi, you can configure this by changing the `max_network_retries` value in `deepl.http_client` (definition [here](https://github.com/DeepLcom/deepl-python/blob/main/deepl/http_client.py#L21C1-L21C20)). Note that it only retries transient errors.

We should probably add this to the README...

**Comment by lukasz-staniszewski** [comment]
Thanks for your response!

Yeah, but it involves changing the library code, which I would prefer not to do. I've seen that the `php` implementation supports specifying [`timeout`](https://github.com/DeepLcom/deepl-php/blob/main/README.md#configuration) more conveniently, hence I hoped for that.

**Comment by JanEbbing** [comment]
What do you mean by "changing the library code"? You can use it like this in your application code:

```python
import deepl
deepl.http_client.max_network_retries = 2
translator = deepl.Translator('my_auth_key')  # Will use 2 retries
```

**Comment by lukasz-staniszewski** [comment]
Yeah, you are entirely right, sorry for my misunderstanding. Thank you for your help!
